### PR TITLE
MessageReceived and ConnectionReceived events minor refactor to support eidtor auto-complete

### PR DESCRIPTION
**Pull request by jasells**
I refactored the MessageReceived event on Udp sockets and ConnectionReceived Tcp to correctly allow auto-complete in editors. Should not affect existing code.

### CODE REVIEW

**Comment by Waty** [comment]
This was fixed in #42

**Comment by jasells** [comment]
Oh, kool!
Guess that's in dev branch?


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jasells** [comment]
Just FYI, my fix is *slightly* different, though not functionally.  

I did not expose a public *member*, I made a public event *property* with accessors, instead of making a public member directly. Functionally, this will make no diff, but it might be useful to know how to declare an event a s a property.

Also, I pulled out a common interface for the MessageReceived event to propagate the changes I made easier.

**Comment by Waty** [comment]
A public event isn't the same as a public member. A public event is more like a public property, it exposes the add and remove methods and has a private delegate member, so it's basically the same as your code, but a whole lot cleaner/shorter.

**Comment by rdavisau** [comment]
As #42 came first and you guys at agree that from the user's perspective they achieve the same thing, I'll close this - but the contribution is appreciated! If I was on top of these PRs we wouldn't have had the conflict so apologies for that. Hoping to get all these changes in over this weekend.

**Pull request closed without merging**
