### PR TITLE
TcpClientSocket.Read/WriteStream now has consistent buffering on both…

### LINKED ISSUE #18: Stream Buffering consistency between WinRT and .NET
Thanks for working on this project, really helpful!

When using same code to target both WinRT and .NET framework, I ran into some issues due to the fact that WinRT uses buffered socket (AsStreamForWrite() without int32 parameter means it uses a default quite huge 16k buffer) while .NET is not (NetworkStream).

Having this disparity is not so good because the way data is gathered in single TCP packet and FlushAsync() behavior are different (esp. bad on .NET since it will start a task with empty NetworkStream.Flush(), but we are forced to do it because WinRT is buffered).

I was thinking it would be better to make it more consistent by either:
- WriteStream is always buffered (i.e. wrap it around a BufferedStream in .NET)
- WriteStream is never buffered (use 0 as parameter).

So far I went with first approach (I could submit a PR) because making it not buffered on WinRT means that you can't do it afterwise (BufferedStream is not publicly exposed).

Another (probably better) option would be to add a parameter to specify buffer size on TcpSocketClient ctor (where 0 means not buffered).

### PR DESCRIPTION
**Pull request by xen2**
… WinRT and .NET. Buffering can also be specified in TcpSocketClient/TcpSocketListener ctor. Fixes #18.

### CODE REVIEW

**Comment by rdavisau** [comment]
Thanks! Will merge and pack in the morning :+1:

**Comment by rdavisau** [comment]
Argh, my OSX partition is temporarily out of action, so I will need to sort that out before I can pack. Hopefully find a solution tonight! :star2:

**Comment by rdavisau** [comment]
Ok, I'm having a look into this, and admittedly haven't worked with `BufferedStream` in the past, but from reading have found that besides consistency of behaviour there are also usage and performance considerations (from reading, better performance can be expected in many cases using `BufferedStream`, but there are limitations on read/write concurrency that might not exist when working with streams directly). 

I see in the .NET implementation `BufferedStream` is only used for the `WriteStream`, whereas on WinRT the buffer size is used for both read and write, can this lead to inconsistent behaviour? I think my preference is to add it for both streams, but do you know if it is safe to add two `BufferedStream`s in the case of .NET? If not sure, then I might do some investigating but I thought I'd check and see whether you might already know about it.

**Comment by Digheads** [comment]
Its not safe adding buffer on the read part. It creates somekind of latency issues. Tested out, works well only with binary reader in that way.

**Pull request merged**
