### PR TITLE
Connect to Named Service + Timeout

### PR DESCRIPTION
**Pull request by Sparksteam**
Added another method to connect to a named remote service, i.e. "http",
and added support to override the default connect timeout.

### CODE REVIEW

**Comment by Sparksteam** [comment]
Oh, and another thing Ryan is I added a getter form the underlying backfield which returns an object because for StreamSockets, I needed access to the StreamSocketControl and StreamSocketInformation attributes.

**Comment by rdavisau** [comment]
I see - but to have access to `StreamSocket` class then, I guess you are doing this part from the WinRT project? If you access `TcpSocketClient` from any platform project, you will see it as it is defined in the corresponding sockets-for-pcl platform project. So (for example), if there were a method on the WinRT `TcpSocketClient` that returned `StreamSocket`, it could be used directly from your own WinRT project, even though it is not visible when coding from your PCL. 

Assuming this your use case, I think it would at least be best to make the .NET and WinRT projects to expose backing fields as the underlying type, and remove the exposing of backing type from the PCL API. 

Then, I wonder what information/control items you are accessing on WinRT and whether there are alternative methods to access the same items on .NET? Adding some support for these settings is [something I once had planned](https://github.com/rdavisau/sockets-for-pcl/blob/b4311d54bbc35bdfd698f28113afd5096b556c18/README.md#planned-features) but had not heard much demand for it and wasn't really familiar enough with it to give it a shot. From memory, it seemed like there wasn't much opportunity for rationalising settings across .NET and WinRT because of conflicting capabilities, but I am not sure now.

**Comment by Sparksteam** [comment]
We access a bunch of stuff in Control and Information in our Universal Windows app.. I would hesitate exposing public methods that are not part of the interface. The TcpClient class exposes the underlying Socket which could be useful for .NET, iOS and Android clients. I guess you could investigate what properties are in common and add the appropriate methods to the interface. But this seems the least painful:).

 

Thanks,

 

Allan

**Comment by rdavisau** [comment]
Hey Allan. Looks like I will have to merge this by hand due to the conflicts with other changes. I'll credit you of course. 

I noticed that the .NET change only supports the "http" service name; after a bit of investigation I decided I will modify that to allow anything TCP-based under the `C:\Windows\System32\drivers\etc\services` file I have on my win10 box here. It's shame the underlying .NET `TcpClient` can't do it, but I think this will be a good enough alternative.

**Comment by Sparksteam** [comment]
Great Ryan, thanks  a lot.






Sent from Windows Mail





From: Ryan Davis
Sent: ‎Tuesday‎, ‎December‎ ‎1‎, ‎2015 ‎12‎:‎04‎ ‎AM
To: rdavisau/sockets-for-pcl
Cc: Allan Chin





Hey Allan. Looks like I will have to merge this by hand due to the conflicts with other changes. I'll credit you of course. 

I noticed that the .NET change only supports the "http" service name; after a bit of investigation I decided I will modify that to allow anything TCP-based under the C:\Windows\System32\drivers\etc\services file I have on my win10 box here. It's shame the underlying .NET TcpClient can't do it, but I think this will be a good enough alternative.

**Comment by Sparksteam** [comment]
Hey Ryan - Is this big merge going to happen soon? Thanks.

**Comment by rdavisau** [comment]
Sorry - I was close and then life got in the way and I lost steam.
I have the weekend free to tick off a bunch of OSS and related obligations, this being top of the list! 
(keep) watch(ing) this space :+1:

**Comment by Sparksteam** [comment]
I hear that Ryan, as long as it's the good life.

**Comment by rdavisau** [comment]
Ok, I've merged this in by hand! I had to make a few changes along the way in order to have some parts interact nicely with everything else that happened in `dev`, mostly around the `CancellationToken` support, but I think it's all sorted. 

Hopefully exposing the backing socket suits your needs; from within a WinRT or .NET project you will see the strongly typed `.Socket` property; from PCL you can get it via `IExposeBackingSocket.Socket`. I'm not keen on exposing the `object` directly on the API surface as it is theoretically an implementation detail; so this is the compromise I came up with. Of course, you can also define an extension method from your own project to expose it without having to do the cast if you want :+1: 

Few more bits to merge in but most of the way there.. :dancers: I'm closing this to keep track of things but you can still reply of course

**Comment by Sparksteam** [comment]
Thanks Ryan, you da man.

 

Yeah, don’t know a better way to expose those underlying properties on the StreamSocket unless you define a bunch of methods in the interface which return “not implemented” for those classes which do not. Let me know when the new version becomes available.

 

Thanks again.

**Comment by rdavisau** [comment]
Alright, 2.0.0-pre is up on NuGet now! :tada: :tada: :tada: 

There's one issue that's holding it back from proper release (the new PCL-friendly `SocketException` isn't co-operating with other changes right now) but otherwise it should be good to use. I will probably leave in pre for a week while I fix this last issue and let it get some exposure to people's usage/scenarios other than what I can test here. 

Thanks for your help and your patience! :+1:

**Comment by Sparksteam** [comment]
Hey Ryan - I'm giving the pre-release a rudimentary spin on all platforms, Android, Win, iOS, and Mac, and all seems good so far except for Mac. During OS X compilation I get a ...

"No overload for method 'ConnectAsync' takes '4' arguments (CS1501)"

See this screenshot, https://www.dropbox.com/s/ppfjz3626kb7pwo/Screen%20Shot%202016-01-15%20at%208.40.03%20AM.png?dl=0

Am I doing something wrong here?

Thanks

**Comment by rdavisau** [comment]
Oops, nothing wrong from your end; I have to build the OSX .dlls from another machine and accidentally packed binaries from the wrong branch! Sorry about that but glad you picked it up. There's a pre2 up now with the correct dlls for OSX :package: 

Thanks again!

**Comment by Sparksteam** [comment]
Much better Ryan, thanks. While I've got you, you wrote a nice article on how to use James Montemagno's Xamarin template extension to build these nice bait-and-switch, NuGet PCL packages. I've been playing around with this for a little while and trying to determine some best practices. In general, what do you create in that project to support OS X? Do you make the iOSUnified a PCL or do you create a new, separate OS X library, or do you do something else? And what do you add to the .nuspec file to pick the correct bits on a Mac? I appreciated your insight? Thanks.

**Comment by rdavisau** [comment]
Hey Allan,

Apologies for the late response!

Happy to help if I can. OSX is a bit more difficult than most platforms, because the Nuget support for the various flavours of Xamarin.Mac/MonoMac is not /quite/ as good. But you can get there with a few caveats. Someone else actually added mac support to sockets-for-pcl but I had to make a few changes so my knowledge is reasonable but not 'expert'.

The key things to keep in mind are:

- Your core PCL (the bait library) needs to be a profile that supports the Mac platform, but as far as I can tell, it 'runs' under proper mono .NET so that is pretty much a given.
- Your 'switch' library for each/any flavours of Mac should be created as a native Xamarin.Mac/Monomac project from Xamarin Studio. If you're lucky, you just want to support Xamarin.Mac Unified, so you just need one for that, and in there you put the proper implementation. 
- For the bait and switch to go nicely your NuGet .nuspec has to be set up just right. [Here] (https://github.com/rdavisau/sockets-for-pcl/blob/v1.2.2/Sockets.Plugin.nuspec#L123-L151) are the relevant lines from sockets-for-pcl as an example. The `src` paths of course need to be correct and point to the compiled native assemblies, but the `target` path is the most important as it determines for each platform whether NuGet will reference the library. Specifically the part after the `lib` path segment is the determiner. For Mac Unified, it needs to be `Xamarin.Mac`, for MonoMac, `MonoMac`. When I last checked, there was no identifier recognised by NuGet for Mac Classic; I just put `Xamarin.Mac.Classic` and ignore the warning that nuget gives about it being invalid. When a user installs the package on Xamarin.Mac classic, they will get the net45 library (if present) instead of the Mac Classic one, and they need to follow the instruction [here](https://github.com/rdavisau/sockets-for-pcl/#platform-considerations) to resolve it. 

I think those are the key things you need to look out for, but let me know if you have any other questions!

**Comment by Sparksteam** [comment]
Thanks for the great information Ryan. I'll let you know how it goes when I get to this point. I'm still working on the implementations and referencing the binaries directly within the various test harnesses:(.

**Comment by Sparksteam** [comment]
Hey Ryan - I haven't tried to deal with the different flavors of MAC yet, But was able to build a NuGet package to support MonoMac/.NET 4.5. Thanks for you valuable info. I have a couplel of more questions, if you don't mind...

1. Using James' Xamarin Plugin Visual Studio template, for the Cross...Current...Create...() and Implementation static methods pattern that's used to assure the NuGet package is referenced, what do you think is the best way to handle a constructor which requires arguments? Just curious to know what you think.

2. Do you have a timeframe for publishing a stable version of the SocketsForPCL?

Thanks,

Allan

**Comment by Sparksteam** [comment]
Hey Ryan - do you think you can publish a stable version of pre2 now? Stable NuGets don't like pre-release dependencies. Thanks.

**Comment by rdavisau** [comment]
Hey Allan - my apologies; as you could guess I have been swamped but this this weekend I will quietly push a 2.0 stable. 

For your first question - I'm not sure I understand 100% what you're asking so I will just explain what I think - you will see from sockets-for-pcl that for all the core classes like `TcpSocketClient` and friends, I don't use the static factory style approach of creating objects, and since you can't enforce constructors via an interface, keeping them in sync between the bait and switch projects is all manual. It's not ideal but it works and gives the user the most pain-free/intuitive api (in my opinion). If I missed the mark on your question let me know, and apologies once again for the delay.

**Comment by Sparksteam** [comment]
Understood Ryan. I'll keep an eye out for 2.0.

Thanks

Allan

**Comment by rdavisau** [comment]
Hi Allan - sockets-for-pcl now has a published 2.0; but it is unlisted. You can still depend on it by specifying the version - `Install-Package rda.SocketsForPCL -Version 2.0.0`, or by specifying 2.0.0 in your packages.config. 

I had some trouble getting my Android tools working so I have opted to publish the latest prerelease but keep in unlisted while I sort out the Android side. This should allow you to depend on it from a stable package nonetheless :tada:

**Comment by Sparksteam** [comment]
Great Ryan, thanks a lot. I'll be on vacation all next week so you have another week to sort out your Android woes;). Keep me posted.

Thanks again.

**Comment by Sparksteam** [comment]
Hey Ryan - do you think you can release a stable version now?

**Comment by Sparksteam** [comment]
Hey Ryan - any chance you can publish a stable version soon? Our build servers may be having a problem with pre-release packages.

Thanks

**Comment by rdavisau** [comment]
It's packed, I gotta check it properly tonight but I'm pretty sure we'll be putting out a stable for it. However, I've dropped Xamarin.Mac Classic and MonoMac because they don't seem to play nice with the new Xamarin tools. Are you targeting Xamarin.Mac Unified? Otherwise there may need to be a 'backporting' exercise to get the new 2.0 features into the older platforms.

**Comment by Sparksteam** [comment]
We plan to target the "Xamarin.Mac .NET 4.5" framework, Ryan. I assume that's the Unified.

Thanks

**Pull request closed without merging**
