### PR TITLE
Connect to Named Service + Timeout

### PR DESCRIPTION
**Pull request by Sparksteam**
Ok, I think I've got the git stuff straightened out. Please review the changes in this pull request for merge consideration into you main project branch. I added a new ConnectAsync() method to connect to a named remote service, i.e. "http", and added support on all ConnectAsync() methods to override the default connect timeout.

### CODE REVIEW

**Comment by rdavisau** [comment]
Hello, thanks for this! 

Almost there with the git stuff - but I need you to target my `dev` branch with your pull request. That's so I can stage all the changes before creating a new version, and have the code in `master` still reflect the current version in the meantime. 

You can't retarget this pull request, you will to close it and create a new one, then choose my `dev` branch rather than `master`.

Thanks again for the contribution! I'll give it a proper review once you send through the new PR :star2:

**Comment by Sparksteam** [comment]
Ugh, I thought I finally had this git stuff licked. Ok, I will close this PR and clone your dev ranch tomorrow.


Thanks for your consideration.






Sent from Windows Mail





From: Ryan Davis
Sent: ‎Thursday‎, ‎November‎ ‎12‎, ‎2015 ‎9‎:‎29‎ ‎PM
To: rdavisau/sockets-for-pcl
Cc: Allan Chin





Hello, thanks for this! 

Almost there with the git stuff - but I need you to target my dev branch with your pull request. That's so I can stage all the changes before creating a new version, and have the code in master still reflect the current version in the meantime. 

You can't retarget this pull request, you will to close it and create a new one, then choose my dev branch rather than master.

Thanks again for the contribution! I'll give it a proper review once you send through the new PR  :star2:

**Comment by rdavisau** [comment]
It's ok - you don't need to reclone or anything, just change the branch in GitHub when you recreate the PR! 👍

**Comment by Sparksteam** [comment]
Closing this PR to re-target the dev branch.

**Comment by Sparksteam** [comment]
Ok Ryan, PR #48 has been created. I hope it’s right. Looks like some conflict resolutions may be in order. Is there something I still need to do on my end?

**Comment by Sparksteam** [comment]
Ryan, please hold off on the merge. After thinking about it some more, it'll be better to pass a CancellationToken instead of just a timeout value as this will also allow the client to cancel the operation as well. I'll make the change 1st thing Monday.


Thanks,


Allan






Sent from Windows Mail





From: Ryan Davis
Sent: ‎Thursday‎, ‎November‎ ‎12‎, ‎2015 ‎9‎:‎29‎ ‎PM
To: rdavisau/sockets-for-pcl
Cc: Allan Chin





Hello, thanks for this! 

Almost there with the git stuff - but I need you to target my dev branch with your pull request. That's so I can stage all the changes before creating a new version, and have the code in master still reflect the current version in the meantime. 

You can't retarget this pull request, you will to close it and create a new one, then choose my dev branch rather than master.

Thanks again for the contribution! I'll give it a proper review once you send through the new PR  :star2:

**Comment by rdavisau** [comment]
No problems Allan - and in case you weren't aware, just pushing your new commits will be enough to update the existing PR. 

If there are conflicts, it is probably due to changes from other outstanding PRs in `dev`. I should be able to sort it out when I'm reviewing things. 

I wasn't going to be working on any of this till after the weekend, so Monday is not a problem.

Thanks again

**Comment by Sparksteam** [comment]
Ok Ryan, I’ve pushed 4 modified files into my master (based off your dev branch). Please take a look and let me know what you think?

 

Thanks,

 

Allan

**Pull request closed without merging**
